#!/usr/bin/env python3
"""
TRELLIS to Xonotic IQM Conversion Pipeline

Converts AI-generated 3D models (GLB from TRELLIS) to Xonotic-compatible IQM format.

Pipeline:
1. GLB → OBJ (via Blender)
2. OBJ → IQM (via IQM compiler)
3. Textures extracted and .skin file generated
4. Model packaged for Xonotic

Usage:
    python3 trellis_to_xonotic.py input.glb output_name [--scale N] [--rotate X,Y,Z]

Example:
    python3 trellis_to_xonotic.py avatar.glb player_model --scale 0.5
"""

import os
import sys
import argparse
import subprocess
import shutil
import tempfile
from pathlib import Path

# Paths
SCRIPT_DIR = Path(__file__).parent.resolve()
IQM_COMPILER = SCRIPT_DIR / "iqm"
GLB_TO_OBJ_SCRIPT = SCRIPT_DIR / "glb_to_obj.py"
BLENDER_PATH = "/usr/bin/blender"

# Xonotic paths
XONOTIC_ROOT = Path("/home/scott/Games/Xonotic")
XONOTIC_DATA = XONOTIC_ROOT / "data"
PK3_BUILD = XONOTIC_ROOT / "pk3_build"

def run_command(cmd, description=""):
    """Run command and handle errors"""
    print(f"\n{'='*60}")
    print(f"  {description}")
    print(f"  Command: {' '.join(str(c) for c in cmd)}")
    print(f"{'='*60}")

    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.stdout:
        print(result.stdout)
    if result.stderr:
        print(result.stderr, file=sys.stderr)

    if result.returncode != 0:
        raise RuntimeError(f"Command failed with exit code {result.returncode}")

    return result

def convert_glb_to_obj(glb_path, obj_path):
    """Convert GLB to OBJ using Blender"""
    cmd = [
        BLENDER_PATH,
        "--background",
        "--python", str(GLB_TO_OBJ_SCRIPT),
        "--",
        str(glb_path),
        str(obj_path)
    ]
    run_command(cmd, "Converting GLB to OBJ via Blender")

def convert_obj_to_iqm(obj_path, iqm_path, scale=None, rotate=None):
    """Convert OBJ to IQM using IQM compiler"""
    cmd = [str(IQM_COMPILER)]

    if scale:
        cmd.extend(["--scale", str(scale)])

    if rotate:
        cmd.extend(["--rotate", rotate])

    cmd.extend([str(iqm_path), str(obj_path)])

    run_command(cmd, "Converting OBJ to IQM")

def package_for_xonotic(iqm_path, model_name, output_dir):
    """Package model with textures for Xonotic pk3"""
    iqm_path = Path(iqm_path)
    output_dir = Path(output_dir)

    # Create model directory in pk3_build
    model_dir = output_dir / "models" / model_name
    model_dir.mkdir(parents=True, exist_ok=True)

    # Copy IQM
    shutil.copy(iqm_path, model_dir / f"{model_name}.iqm")
    print(f"Copied IQM to: {model_dir / f'{model_name}.iqm'}")

    # Copy associated files (textures, skin)
    source_dir = iqm_path.parent
    for ext in ['.skin', '.png', '.jpg', '.tga']:
        for f in source_dir.glob(f"*{ext}"):
            dest = model_dir / f.name
            shutil.copy(f, dest)
            print(f"Copied: {f.name} → {dest}")

    # Create default shader if textures exist
    textures = list(model_dir.glob("*.png")) + list(model_dir.glob("*.jpg"))
    if textures:
        shader_path = output_dir / "scripts" / f"{model_name}.shader"
        shader_path.parent.mkdir(parents=True, exist_ok=True)

        with open(shader_path, 'w') as f:
            for tex in textures:
                tex_stem = tex.stem
                f.write(f"""
models/{model_name}/{tex_stem}
{{
    {{
        map models/{model_name}/{tex.name}
        rgbGen lightingDiffuse
    }}
}}
""")
        print(f"Created shader: {shader_path}")

    return model_dir

def create_entity_def(model_name, output_dir):
    """Create entity definition for map editor"""
    output_dir = Path(output_dir)
    def_path = output_dir / "scripts" / "entities" / f"{model_name}.def"
    def_path.parent.mkdir(parents=True, exist_ok=True)

    with open(def_path, 'w') as f:
        f.write(f"""/*QUAKED misc_{model_name} (1 0.5 0) (-16 -16 0) (16 16 32)
AI-generated model: {model_name}
Generated by TRELLIS → IQM pipeline

Keys:
"model" : "models/{model_name}/{model_name}.iqm"
"angles" : "pitch yaw roll"
"scale" : "uniform scale factor"
*/
""")
    print(f"Created entity definition: {def_path}")

def main():
    parser = argparse.ArgumentParser(
        description="Convert TRELLIS GLB to Xonotic IQM format"
    )
    parser.add_argument("input_glb", help="Input GLB file from TRELLIS")
    parser.add_argument("model_name", help="Output model name (e.g., 'player_avatar')")
    parser.add_argument("--scale", type=float, default=None,
                       help="Scale factor for the model")
    parser.add_argument("--rotate", type=str, default=None,
                       help="Rotation as X,Y,Z in degrees (e.g., '0,90,0')")
    parser.add_argument("--output-dir", type=str, default=None,
                       help=f"Output directory (default: {PK3_BUILD})")
    parser.add_argument("--keep-temp", action="store_true",
                       help="Keep temporary files")

    args = parser.parse_args()

    input_glb = Path(args.input_glb).resolve()
    if not input_glb.exists():
        print(f"Error: Input file not found: {input_glb}")
        sys.exit(1)

    output_dir = Path(args.output_dir) if args.output_dir else PK3_BUILD

    print(f"""
╔══════════════════════════════════════════════════════════════════╗
║           TRELLIS → Xonotic IQM Conversion Pipeline              ║
╠══════════════════════════════════════════════════════════════════╣
║  Input:  {str(input_glb):<54} ║
║  Output: {args.model_name:<54} ║
║  Scale:  {str(args.scale or 'default'):<54} ║
║  Rotate: {str(args.rotate or 'none'):<54} ║
╚══════════════════════════════════════════════════════════════════╝
""")

    # Create temp directory for intermediate files
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)

        obj_path = temp_path / f"{args.model_name}.obj"
        iqm_path = temp_path / f"{args.model_name}.iqm"

        try:
            # Step 1: GLB → OBJ
            convert_glb_to_obj(input_glb, obj_path)

            if not obj_path.exists():
                raise RuntimeError("OBJ conversion failed - no output file")

            # Step 2: OBJ → IQM
            convert_obj_to_iqm(obj_path, iqm_path, args.scale, args.rotate)

            if not iqm_path.exists():
                raise RuntimeError("IQM conversion failed - no output file")

            # Step 3: Package for Xonotic
            model_dir = package_for_xonotic(iqm_path, args.model_name, output_dir)

            # Step 4: Create entity definition
            create_entity_def(args.model_name, output_dir)

            print(f"""
╔══════════════════════════════════════════════════════════════════╗
║                    ✓ CONVERSION COMPLETE                         ║
╠══════════════════════════════════════════════════════════════════╣
║  Model: {str(model_dir):<55} ║
║                                                                  ║
║  To use in Xonotic:                                              ║
║  1. Create pk3: cd {str(output_dir):<38} ║
║                 zip -r {args.model_name}.pk3 models/ scripts/    ║
║  2. Copy to: ~/.xonotic/data/                                    ║
║  3. In-game: /loadmodel models/{args.model_name}/{args.model_name}.iqm  ║
╚══════════════════════════════════════════════════════════════════╝
""")

        except Exception as e:
            print(f"\n❌ Error: {e}")
            if args.keep_temp:
                print(f"Temp files preserved in: {temp_path}")
                # Copy temp to permanent location
                preserve_dir = Path("/tmp/trellis_convert_debug")
                preserve_dir.mkdir(exist_ok=True)
                for f in temp_path.iterdir():
                    shutil.copy(f, preserve_dir)
                print(f"Debug files copied to: {preserve_dir}")
            sys.exit(1)

if __name__ == "__main__":
    main()
