"""Generate the RustChain Validator Node Pillar prop package.

The output is an original low-poly IQM prop for bounty #14015:
pk3_build/models/props/rustchain_validator_node_pillar/.
"""

from __future__ import annotations

import math
import struct
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
PROP_NAME = "rustchain_validator_node_pillar"
OUT = ROOT / "pk3_build" / "models" / "props" / PROP_NAME

MODEL_FILE = OUT / f"{PROP_NAME}.iqm"
SKIN_FILE = OUT / f"{PROP_NAME}_0.skin"
SOURCE_OBJ_FILE = OUT / f"{PROP_NAME}_source.obj"
SOURCE_MTL_FILE = OUT / f"{PROP_NAME}_source.mtl"
PREVIEW_FILE = OUT / f"{PROP_NAME}_preview.png"

MATERIALS = {
    "pillar_metal": {
        "texture": "validator_node_pillar_metal.tga",
        "color": (34, 39, 43),
        "kd": (0.20, 0.22, 0.24),
    },
    "pillar_gold": {
        "texture": "validator_node_pillar_gold.tga",
        "color": (227, 166, 55),
        "kd": (0.86, 0.57, 0.18),
    },
    "pillar_glow": {
        "texture": "validator_node_pillar_glow.tga",
        "color": (255, 118, 42),
        "kd": (1.00, 0.42, 0.10),
    },
    "pillar_glass": {
        "texture": "validator_node_pillar_glass.tga",
        "color": (46, 187, 214),
        "kd": (0.16, 0.62, 0.74),
    },
}

README_TEXT = """# RustChain Validator Node Pillar prop

Original low-poly set-dressing prop for the Xonotic RustChain Arena prop bounty:
https://github.com/Scottcjn/rustchain-bounties/issues/14015

## Package

| File | Purpose |
| --- | --- |
| `rustchain_validator_node_pillar.iqm` | Static IQM model written directly from deterministic procedural geometry |
| `rustchain_validator_node_pillar_0.skin` | DarkPlaces/Xonotic material-to-texture mapping |
| `validator_node_pillar_metal.tga` | 256x256 panel metal diffuse texture |
| `validator_node_pillar_gold.tga` | 256x256 RTC trim and coin texture |
| `validator_node_pillar_glow.tga` | 256x256 emissive orange/cyan status-strip texture |
| `validator_node_pillar_glass.tga` | 256x256 holographic blue glass texture |
| `rustchain_validator_node_pillar_preview.png` | Preview render and texture swatches |
| `rustchain_validator_node_pillar_source.obj` | Reproducible source mesh generated by the Python script |
| `rustchain_validator_node_pillar_source.mtl` | Source material table for the generated OBJ mesh |

## Design

The model implements the **Validator node pillar / capture point** wishlist item.
It is a compact arena prop with:

- octagonal armored base
- vertical validator core
- four glowing consensus strips
- gold RTC top token
- low-poly top cap and corner rails

The geometry is procedural and original. It does not embed external meshes,
samples, textures, or AI-generated model files.

## Regeneration

From the repository root:

```powershell
python tools/generate_rustchain_validator_node_pillar_prop.py
```

The script writes the OBJ/MTL source, TGA textures, PNG preview, README,
LICENSE, skin file, and static IQM v2 model. It does not require Blender or
the bundled IQM executable.
"""

LICENSE_TEXT = """RustChain Validator Node Pillar prop

Copyright 2026

This model, texture pack, preview image, and deterministic procedural source
are licensed under the Creative Commons Attribution-ShareAlike 4.0
International License (CC-BY-SA-4.0).

You are free to share and adapt the material for any purpose, even
commercially, provided attribution is given and adaptations are distributed
under the same license.

License summary and legal code:
https://creativecommons.org/licenses/by-sa/4.0/
"""


class ObjBuilder:
    def __init__(self) -> None:
        self.vertices: list[tuple[float, float, float]] = []
        self.uvs: list[tuple[float, float]] = []
        self.faces: list[tuple[str, tuple[tuple[int, int], tuple[int, int], tuple[int, int]]]] = []

    def _add_vertex(self, point: tuple[float, float, float], uv: tuple[float, float]) -> tuple[int, int]:
        self.vertices.append(point)
        self.uvs.append(uv)
        return len(self.vertices), len(self.uvs)

    def add_tri(
        self,
        material: str,
        points: tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]],
        uvs: tuple[tuple[float, float], tuple[float, float], tuple[float, float]] = ((0.0, 0.0), (1.0, 0.0), (0.5, 1.0)),
    ) -> None:
        self.faces.append((material, tuple(self._add_vertex(point, uv) for point, uv in zip(points, uvs))))

    def add_quad(
        self,
        material: str,
        points: tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]],
    ) -> None:
        uvs = ((0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0))
        self.add_tri(material, (points[0], points[1], points[2]), (uvs[0], uvs[1], uvs[2]))
        self.add_tri(material, (points[0], points[2], points[3]), (uvs[0], uvs[2], uvs[3]))

    def add_box(
        self,
        center: tuple[float, float, float],
        size: tuple[float, float, float],
        material: str,
    ) -> None:
        cx, cy, cz = center
        sx, sy, sz = (s / 2.0 for s in size)
        x0, x1 = cx - sx, cx + sx
        y0, y1 = cy - sy, cy + sy
        z0, z1 = cz - sz, cz + sz
        self.add_quad(material, ((x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1)))
        self.add_quad(material, ((x1, y0, z0), (x0, y0, z0), (x0, y0, z1), (x1, y0, z1)))
        self.add_quad(material, ((x1, y1, z0), (x1, y0, z0), (x1, y0, z1), (x1, y1, z1)))
        self.add_quad(material, ((x0, y0, z0), (x0, y1, z0), (x0, y1, z1), (x0, y0, z1)))
        self.add_quad(material, ((x0, y0, z1), (x0, y1, z1), (x1, y1, z1), (x1, y0, z1)))
        self.add_quad(material, ((x0, y1, z0), (x0, y0, z0), (x1, y0, z0), (x1, y1, z0)))

    def add_cylinder(
        self,
        center: tuple[float, float, float],
        radius: float,
        height: float,
        segments: int,
        side_material: str,
        cap_material: str | None = None,
        phase: float = 0.0,
    ) -> None:
        cx, cy, cz = center
        z0, z1 = cz - height / 2.0, cz + height / 2.0
        cap = cap_material or side_material
        bottom_center = (cx, cy, z0)
        top_center = (cx, cy, z1)

        ring: list[tuple[float, float, float]] = []
        for i in range(segments):
            a = phase + (math.tau * i / segments)
            ring.append((cx + math.cos(a) * radius, cy + math.sin(a) * radius, 0.0))

        for i in range(segments):
            p0 = ring[i]
            p1 = ring[(i + 1) % segments]
            bottom0 = (p0[0], p0[1], z0)
            bottom1 = (p1[0], p1[1], z0)
            top0 = (p0[0], p0[1], z1)
            top1 = (p1[0], p1[1], z1)
            u0 = i / segments
            u1 = (i + 1) / segments
            self.add_tri(side_material, (bottom0, bottom1, top1), ((u0, 0.0), (u1, 0.0), (u1, 1.0)))
            self.add_tri(side_material, (bottom0, top1, top0), ((u0, 0.0), (u1, 1.0), (u0, 1.0)))
            self.add_tri(cap, (top_center, top0, top1), ((0.5, 0.5), (0.0, 1.0), (1.0, 1.0)))
            self.add_tri(cap, (bottom_center, bottom1, bottom0), ((0.5, 0.5), (1.0, 0.0), (0.0, 0.0)))

    def write(self, path: Path, mtl_name: str) -> None:
        lines = [f"mtllib {mtl_name}", f"o {PROP_NAME}"]
        lines.extend(f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in self.vertices)
        lines.extend(f"vt {u:.6f} {v:.6f}" for u, v in self.uvs)
        current_material = None
        for material, face in self.faces:
            if material != current_material:
                lines.append(f"usemtl {material}")
                current_material = material
            verts = " ".join(f"{vi}/{ti}" for vi, ti in face)
            lines.append(f"f {verts}")
        path.write_text("\n".join(lines) + "\n", encoding="ascii")


def align(value: int, boundary: int = 4) -> int:
    return (value + boundary - 1) // boundary * boundary


def normal_for(points: tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]]) -> tuple[float, float, float]:
    ax, ay, az = points[0]
    bx, by, bz = points[1]
    cx, cy, cz = points[2]
    ux, uy, uz = bx - ax, by - ay, bz - az
    vx, vy, vz = cx - ax, cy - ay, cz - az
    nx = uy * vz - uz * vy
    ny = uz * vx - ux * vz
    nz = ux * vy - uy * vx
    length = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
    return nx / length, ny / length, nz / length


def write_iqm_direct(path: Path, mesh: ObjBuilder) -> None:
    strings = ["", PROP_NAME, *MATERIALS.keys()]
    offsets: dict[str, int] = {}
    cursor = 0
    text_parts: list[bytes] = []
    for item in strings:
        offsets[item] = cursor
        encoded = item.encode("ascii") + b"\0"
        text_parts.append(encoded)
        cursor += len(encoded)
    text = b"".join(text_parts)

    positions: list[tuple[float, float, float]] = []
    texcoords: list[tuple[float, float]] = []
    normals: list[tuple[float, float, float]] = []
    triangles: list[tuple[int, int, int]] = []
    mesh_rows: list[tuple[int, int, int, int, int, int]] = []

    for material in MATERIALS:
        first_vertex = len(positions)
        first_triangle = len(triangles)
        for face_material, face in mesh.faces:
            if face_material != material:
                continue
            points = tuple(mesh.vertices[vertex_index - 1] for vertex_index, _ in face)
            uvs = tuple(mesh.uvs[uv_index - 1] for _, uv_index in face)
            normal = normal_for(points)
            tri = []
            for point, uv in zip(points, uvs):
                positions.append(point)
                texcoords.append(uv)
                normals.append(normal)
                tri.append(len(positions) - 1)
            triangles.append(tuple(tri))
        mesh_rows.append(
            (
                offsets[PROP_NAME],
                offsets[material],
                first_vertex,
                len(positions) - first_vertex,
                first_triangle,
                len(triangles) - first_triangle,
            )
        )

    comment = b"Deterministic Python-generated static IQM for RustChain validator node pillar.\0"
    header_size = 16 + 27 * 4
    num_meshes = len(mesh_rows)
    num_vertexarrays = 3
    num_vertices = len(positions)
    num_triangles = len(triangles)

    ofs_text = align(header_size)
    ofs_meshes = align(ofs_text + len(text))
    ofs_vertexarrays = align(ofs_meshes + num_meshes * 6 * 4)
    ofs_triangles = align(ofs_vertexarrays + num_vertexarrays * 5 * 4)
    ofs_positions = align(ofs_triangles + num_triangles * 3 * 4)
    ofs_texcoords = align(ofs_positions + num_vertices * 3 * 4)
    ofs_normals = align(ofs_texcoords + num_vertices * 2 * 4)
    ofs_comment = align(ofs_normals + num_vertices * 3 * 4)
    filesize = align(ofs_comment + len(comment))

    header = struct.pack(
        "<16s27I",
        b"INTERQUAKEMODEL\0",
        2,
        filesize,
        0,
        len(text),
        ofs_text,
        num_meshes,
        ofs_meshes,
        num_vertexarrays,
        num_vertices,
        ofs_vertexarrays,
        num_triangles,
        ofs_triangles,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        len(comment),
        ofs_comment,
        0,
        0,
    )
    vertex_arrays = b"".join(
        [
            struct.pack("<5I", 0, 0, 7, 3, ofs_positions),
            struct.pack("<5I", 1, 0, 7, 2, ofs_texcoords),
            struct.pack("<5I", 2, 0, 7, 3, ofs_normals),
        ]
    )

    blob = bytearray(filesize)
    chunks = [
        (0, header),
        (ofs_text, text),
        (ofs_meshes, b"".join(struct.pack("<6I", *row) for row in mesh_rows)),
        (ofs_vertexarrays, vertex_arrays),
        (ofs_triangles, b"".join(struct.pack("<3I", *tri) for tri in triangles)),
        (ofs_positions, b"".join(struct.pack("<3f", *point) for point in positions)),
        (ofs_texcoords, b"".join(struct.pack("<2f", *uv) for uv in texcoords)),
        (ofs_normals, b"".join(struct.pack("<3f", *normal) for normal in normals)),
        (ofs_comment, comment),
    ]
    for offset, data in chunks:
        blob[offset : offset + len(data)] = data
    path.write_bytes(blob)


def font(size: int) -> ImageFont.ImageFont:
    candidates = (
        "C:/Windows/Fonts/segoeuib.ttf",
        "C:/Windows/Fonts/segoeui.ttf",
        "C:/Windows/Fonts/arial.ttf",
    )
    for candidate in candidates:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def write_textures() -> None:
    for name, spec in MATERIALS.items():
        image = Image.new("RGB", (256, 256), spec["color"])
        draw = ImageDraw.Draw(image)
        if name == "pillar_metal":
            for x in range(0, 256, 32):
                draw.line((x, 0, x, 255), fill=(54, 60, 63), width=2)
            for y in range(0, 256, 32):
                draw.line((0, y, 255, y), fill=(18, 22, 24), width=2)
            for i in range(8):
                y = 20 + i * 28
                draw.rectangle((24, y, 232, y + 10), outline=(75, 84, 82), width=1)
        elif name == "pillar_gold":
            for i in range(0, 256, 16):
                shade = 120 + (i % 64)
                draw.line((0, i, 255, i + 48), fill=(min(255, shade + 80), min(220, shade + 38), 46), width=4)
            draw.ellipse((54, 54, 202, 202), outline=(255, 225, 126), width=9)
            draw.text((91, 104), "RTC", fill=(74, 43, 15), font=font(34))
        elif name == "pillar_glow":
            image = Image.new("RGB", (256, 256), (9, 10, 12))
            draw = ImageDraw.Draw(image)
            for x in (40, 92, 144, 196):
                draw.rounded_rectangle((x, 18, x + 18, 238), radius=7, fill=(255, 114, 34))
                draw.line((x + 9, 20, x + 9, 236), fill=(255, 207, 87), width=3)
            for y in range(30, 250, 44):
                draw.line((22, y, 234, y), fill=(38, 194, 212), width=2)
        elif name == "pillar_glass":
            for i in range(0, 256, 18):
                draw.line((i, 0, 0, i), fill=(91, 220, 236), width=2)
                draw.line((255, i, i, 255), fill=(22, 94, 126), width=2)
            draw.rectangle((18, 18, 238, 238), outline=(168, 247, 255), width=5)
        image.save(OUT / spec["texture"])


def write_material_file(path: Path) -> None:
    lines: list[str] = []
    for material, spec in MATERIALS.items():
        kd = spec["kd"]
        lines.extend(
            [
                f"newmtl {material}",
                f"Kd {kd[0]:.3f} {kd[1]:.3f} {kd[2]:.3f}",
                f"map_Kd {spec['texture']}",
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="ascii")


def build_mesh() -> ObjBuilder:
    mesh = ObjBuilder()
    mesh.add_cylinder((0, 0, 0.12), 1.15, 0.24, 8, "pillar_metal", "pillar_gold", phase=math.pi / 8)
    mesh.add_cylinder((0, 0, 0.30), 0.92, 0.12, 8, "pillar_gold", "pillar_gold", phase=math.pi / 8)
    mesh.add_box((0, 0, 1.08), (0.62, 0.62, 1.58), "pillar_metal")
    mesh.add_box((0.325, 0, 1.08), (0.045, 0.44, 1.32), "pillar_glow")
    mesh.add_box((-0.325, 0, 1.08), (0.045, 0.44, 1.32), "pillar_glow")
    mesh.add_box((0, 0.325, 1.08), (0.44, 0.045, 1.32), "pillar_glow")
    mesh.add_box((0, -0.325, 1.08), (0.44, 0.045, 1.32), "pillar_glow")
    for x in (-0.43, 0.43):
        for y in (-0.43, 0.43):
            mesh.add_box((x, y, 1.06), (0.10, 0.10, 1.38), "pillar_gold")
    mesh.add_cylinder((0, 0, 1.55), 0.68, 0.06, 16, "pillar_glass", "pillar_glass")
    mesh.add_cylinder((0, 0, 1.94), 0.76, 0.16, 12, "pillar_metal", "pillar_gold", phase=math.pi / 12)
    mesh.add_cylinder((0, 0, 2.09), 0.48, 0.08, 24, "pillar_gold", "pillar_gold")
    mesh.add_cylinder((0, 0, 2.18), 0.34, 0.06, 24, "pillar_glow", "pillar_glow")
    for x, y in ((0.0, 0.62), (0.0, -0.62), (0.62, 0.0), (-0.62, 0.0)):
        mesh.add_box((x, y, 2.13), (0.07, 0.07, 0.36), "pillar_glow")
    return mesh


def write_skin() -> None:
    lines = [
        f"{material},models/props/{PROP_NAME}/{Path(spec['texture']).stem}"
        for material, spec in MATERIALS.items()
    ]
    SKIN_FILE.write_text("\n".join(lines) + "\n", encoding="ascii")


def write_preview() -> None:
    image = Image.new("RGB", (1280, 720), (18, 23, 26))
    draw = ImageDraw.Draw(image)
    draw.rectangle((0, 0, 1280, 720), fill=(18, 23, 26))
    for y in range(420, 720, 28):
        draw.line((0, y, 1280, y - 180), fill=(28, 38, 42), width=1)
    for x in range(-200, 1400, 80):
        draw.line((x, 720, x + 520, 360), fill=(25, 34, 38), width=1)

    cx, base_y = 520, 535
    draw.polygon([(cx - 190, base_y), (cx, base_y - 70), (cx + 190, base_y), (cx, base_y + 70)], fill=(48, 55, 58), outline=(218, 142, 45))
    draw.polygon([(cx - 115, base_y - 80), (cx, base_y - 125), (cx + 115, base_y - 80), (cx, base_y - 35)], fill=(192, 129, 42), outline=(255, 210, 112))
    draw.rectangle((cx - 75, 205, cx + 75, base_y - 72), fill=(39, 43, 45), outline=(104, 114, 110), width=3)
    for offset in (-90, 90):
        draw.rectangle((cx + offset - 11, 230, cx + offset + 11, 455), fill=(255, 111, 34))
        draw.line((cx + offset, 235, cx + offset, 450), fill=(255, 225, 104), width=4)
    for offset in (-95, 95):
        draw.rectangle((cx + offset - 12, 205, cx + offset + 12, 486), fill=(203, 143, 47))
    draw.ellipse((cx - 130, 170, cx + 130, 230), fill=(54, 172, 190), outline=(156, 246, 255), width=4)
    draw.polygon([(cx - 130, 185), (cx, 145), (cx + 130, 185), (cx + 95, 245), (cx - 95, 245)], fill=(56, 60, 61), outline=(224, 159, 58))
    draw.ellipse((cx - 78, 120, cx + 78, 195), fill=(222, 154, 46), outline=(255, 225, 119), width=5)
    draw.text((cx - 42, 143), "RTC", fill=(70, 38, 12), font=font(31))
    draw.ellipse((cx - 48, 105, cx + 48, 150), fill=(255, 109, 31), outline=(255, 224, 96), width=3)

    draw.text((760, 104), "RustChain Validator", fill=(241, 206, 126), font=font(48))
    draw.text((760, 160), "Node Pillar / Capture Point", fill=(186, 218, 220), font=font(30))
    draw.text((760, 212), "Original low-poly IQM prop", fill=(150, 164, 166), font=font(24))
    draw.text((760, 246), "Bounty #14015 - 7 RTC prop lane", fill=(150, 164, 166), font=font(24))

    swatches = [
        ("metal", MATERIALS["pillar_metal"]["color"]),
        ("gold", MATERIALS["pillar_gold"]["color"]),
        ("glow", MATERIALS["pillar_glow"]["color"]),
        ("glass", MATERIALS["pillar_glass"]["color"]),
    ]
    for i, (label, color) in enumerate(swatches):
        y = 330 + i * 54
        draw.rectangle((768, y, 832, y + 34), fill=color, outline=(220, 230, 226))
        draw.text((850, y + 2), label, fill=(212, 222, 222), font=font(24))
    image.save(PREVIEW_FILE)


def generate() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    write_textures()
    write_material_file(SOURCE_MTL_FILE)
    mesh = build_mesh()
    mesh.write(SOURCE_OBJ_FILE, SOURCE_MTL_FILE.name)
    write_iqm_direct(MODEL_FILE, mesh)
    write_skin()
    write_preview()
    (OUT / "README.md").write_text(README_TEXT, encoding="utf-8")
    (OUT / "LICENSE").write_text(LICENSE_TEXT, encoding="utf-8")


if __name__ == "__main__":
    generate()
    print(f"Wrote {PROP_NAME} prop package to {OUT}")
