"""Generate the RustChain Hash Crate prop package.

The output is an original low-poly IQM prop for bounty #14015:
pk3_build/models/props/rustchain_hash_crate/.
"""

from __future__ import annotations

import math
import struct
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
PROP_NAME = "rustchain_hash_crate"
OUT = ROOT / "pk3_build" / "models" / "props" / PROP_NAME

MODEL_FILE = OUT / f"{PROP_NAME}.iqm"
SKIN_FILE = OUT / f"{PROP_NAME}_0.skin"
SOURCE_OBJ_FILE = OUT / f"{PROP_NAME}_source.obj"
SOURCE_MTL_FILE = OUT / f"{PROP_NAME}_source.mtl"
PREVIEW_FILE = OUT / f"{PROP_NAME}_preview.png"

MATERIALS = {
    "crate_iron": {
        "texture": "hash_crate_iron.tga",
        "color": (38, 45, 46),
        "kd": (0.17, 0.20, 0.20),
    },
    "hash_panels": {
        "texture": "hash_crate_panels.tga",
        "color": (82, 96, 92),
        "kd": (0.34, 0.39, 0.37),
    },
    "rtc_glow": {
        "texture": "hash_crate_glow.tga",
        "color": (34, 214, 216),
        "kd": (0.08, 0.76, 0.78),
    },
    "warning_stripe": {
        "texture": "hash_crate_warning.tga",
        "color": (233, 139, 32),
        "kd": (0.90, 0.45, 0.08),
    },
}

README_TEXT = """# RustChain Hash Crate prop

Original low-poly set-dressing prop for the Xonotic RustChain Arena prop bounty #14015:
https://github.com/Scottcjn/rustchain-bounties/issues/14015

## Package

| File | Purpose |
| --- | --- |
| `rustchain_hash_crate.iqm` | Static IQM model written directly from deterministic procedural geometry |
| `rustchain_hash_crate_0.skin` | DarkPlaces/Xonotic material-to-texture mapping |
| `hash_crate_iron.tga` | 256x256 dark iron frame texture |
| `hash_crate_panels.tga` | 256x256 crate side panel texture |
| `hash_crate_glow.tga` | 256x256 cyan hash-core glow texture |
| `hash_crate_warning.tga` | 256x256 orange hazard-stripe texture |
| `rustchain_hash_crate_preview.png` | Preview render and texture swatches |
| `rustchain_hash_crate_source.obj` | Reproducible source mesh generated by the Python script |
| `rustchain_hash_crate_source.mtl` | Source material table for the generated OBJ mesh |

## Design

The model implements the **hash crate** wishlist item. It is a compact arena
supply crate with a dark metal frame, reinforced panel faces, cyan hash-core
windows, orange hazard corner plates, and a raised top plate marked HASH.

The geometry is procedural and original. It does not embed external meshes,
samples, textures, or AI-generated model files.

## Regeneration

From the repository root:

```powershell
python tools/generate_rustchain_hash_crate_prop.py
```

The script writes the OBJ/MTL source, TGA textures, PNG preview, README,
LICENSE, skin file, and static IQM v2 model. It does not require Blender or
the bundled IQM executable.
"""

LICENSE_TEXT = """RustChain Hash Crate prop

Copyright 2026

This model, texture pack, preview image, and deterministic procedural source
are licensed under the Creative Commons Attribution-ShareAlike 4.0
International License (CC-BY-SA-4.0).

You are free to share and adapt the material for any purpose, even
commercially, provided attribution is given and adaptations are distributed
under the same license.

License summary and legal code:
https://creativecommons.org/licenses/by-sa/4.0/
"""


class ObjBuilder:
    def __init__(self) -> None:
        self.vertices: list[tuple[float, float, float]] = []
        self.uvs: list[tuple[float, float]] = []
        self.faces: list[tuple[str, tuple[tuple[int, int], tuple[int, int], tuple[int, int]]]] = []

    def _add_vertex(self, point: tuple[float, float, float], uv: tuple[float, float]) -> tuple[int, int]:
        self.vertices.append(point)
        self.uvs.append(uv)
        return len(self.vertices), len(self.uvs)

    def add_tri(
        self,
        material: str,
        points: tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]],
        uvs: tuple[tuple[float, float], tuple[float, float], tuple[float, float]] = ((0.0, 0.0), (1.0, 0.0), (0.5, 1.0)),
    ) -> None:
        self.faces.append((material, tuple(self._add_vertex(point, uv) for point, uv in zip(points, uvs))))

    def add_quad(
        self,
        material: str,
        points: tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]],
    ) -> None:
        uvs = ((0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0))
        self.add_tri(material, (points[0], points[1], points[2]), (uvs[0], uvs[1], uvs[2]))
        self.add_tri(material, (points[0], points[2], points[3]), (uvs[0], uvs[2], uvs[3]))

    def add_box(self, center: tuple[float, float, float], size: tuple[float, float, float], material: str) -> None:
        cx, cy, cz = center
        sx, sy, sz = (s / 2.0 for s in size)
        x0, x1 = cx - sx, cx + sx
        y0, y1 = cy - sy, cy + sy
        z0, z1 = cz - sz, cz + sz
        self.add_quad(material, ((x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1)))
        self.add_quad(material, ((x1, y0, z0), (x0, y0, z0), (x0, y0, z1), (x1, y0, z1)))
        self.add_quad(material, ((x1, y1, z0), (x1, y0, z0), (x1, y0, z1), (x1, y1, z1)))
        self.add_quad(material, ((x0, y0, z0), (x0, y1, z0), (x0, y1, z1), (x0, y0, z1)))
        self.add_quad(material, ((x0, y0, z1), (x0, y1, z1), (x1, y1, z1), (x1, y0, z1)))
        self.add_quad(material, ((x0, y1, z0), (x0, y0, z0), (x1, y0, z0), (x1, y1, z0)))

    def add_cylinder(
        self,
        center: tuple[float, float, float],
        radius: float,
        height: float,
        segments: int,
        side_material: str,
        cap_material: str | None = None,
        phase: float = 0.0,
    ) -> None:
        cx, cy, cz = center
        z0, z1 = cz - height / 2.0, cz + height / 2.0
        cap = cap_material or side_material
        bottom_center = (cx, cy, z0)
        top_center = (cx, cy, z1)
        ring = []
        for i in range(segments):
            a = phase + math.tau * i / segments
            ring.append((cx + math.cos(a) * radius, cy + math.sin(a) * radius, 0.0))
        for i in range(segments):
            p0 = ring[i]
            p1 = ring[(i + 1) % segments]
            bottom0 = (p0[0], p0[1], z0)
            bottom1 = (p1[0], p1[1], z0)
            top0 = (p0[0], p0[1], z1)
            top1 = (p1[0], p1[1], z1)
            u0 = i / segments
            u1 = (i + 1) / segments
            self.add_tri(side_material, (bottom0, bottom1, top1), ((u0, 0.0), (u1, 0.0), (u1, 1.0)))
            self.add_tri(side_material, (bottom0, top1, top0), ((u0, 0.0), (u1, 1.0), (u0, 1.0)))
            self.add_tri(cap, (top_center, top0, top1), ((0.5, 0.5), (0.0, 1.0), (1.0, 1.0)))
            self.add_tri(cap, (bottom_center, bottom1, bottom0), ((0.5, 0.5), (1.0, 0.0), (0.0, 0.0)))

    def write(self, path: Path, mtl_name: str) -> None:
        lines = [f"mtllib {mtl_name}", f"o {PROP_NAME}"]
        lines.extend(f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in self.vertices)
        lines.extend(f"vt {u:.6f} {v:.6f}" for u, v in self.uvs)
        current_material = None
        for material, face in self.faces:
            if material != current_material:
                lines.append(f"usemtl {material}")
                current_material = material
            lines.append("f " + " ".join(f"{vi}/{ti}" for vi, ti in face))
        path.write_text("\n".join(lines) + "\n", encoding="ascii")


def align(value: int, boundary: int = 4) -> int:
    return (value + boundary - 1) // boundary * boundary


def normal_for(points: tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]]) -> tuple[float, float, float]:
    ax, ay, az = points[0]
    bx, by, bz = points[1]
    cx, cy, cz = points[2]
    ux, uy, uz = bx - ax, by - ay, bz - az
    vx, vy, vz = cx - ax, cy - ay, cz - az
    nx = uy * vz - uz * vy
    ny = uz * vx - ux * vz
    nz = ux * vy - uy * vx
    length = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
    return nx / length, ny / length, nz / length


def write_iqm_direct(path: Path, mesh: ObjBuilder) -> None:
    strings = ["", PROP_NAME, *MATERIALS.keys()]
    offsets: dict[str, int] = {}
    cursor = 0
    text_parts = []
    for item in strings:
        offsets[item] = cursor
        encoded = item.encode("ascii") + b"\0"
        text_parts.append(encoded)
        cursor += len(encoded)
    text = b"".join(text_parts)

    positions: list[tuple[float, float, float]] = []
    texcoords: list[tuple[float, float]] = []
    normals: list[tuple[float, float, float]] = []
    triangles: list[tuple[int, int, int]] = []
    mesh_rows: list[tuple[int, int, int, int, int, int]] = []
    for material in MATERIALS:
        first_vertex = len(positions)
        first_triangle = len(triangles)
        for face_material, face in mesh.faces:
            if face_material != material:
                continue
            points = tuple(mesh.vertices[vertex_index - 1] for vertex_index, _ in face)
            uvs = tuple(mesh.uvs[uv_index - 1] for _, uv_index in face)
            normal = normal_for(points)
            tri = []
            for point, uv in zip(points, uvs):
                positions.append(point)
                texcoords.append(uv)
                normals.append(normal)
                tri.append(len(positions) - 1)
            triangles.append(tuple(tri))
        mesh_rows.append((offsets[PROP_NAME], offsets[material], first_vertex, len(positions) - first_vertex, first_triangle, len(triangles) - first_triangle))

    comment = b"Deterministic Python-generated static IQM for RustChain hash crate.\0"
    header_size = 16 + 27 * 4
    num_vertexarrays = 3
    ofs_text = align(header_size)
    ofs_meshes = align(ofs_text + len(text))
    ofs_vertexarrays = align(ofs_meshes + len(mesh_rows) * 6 * 4)
    ofs_triangles = align(ofs_vertexarrays + num_vertexarrays * 5 * 4)
    ofs_positions = align(ofs_triangles + len(triangles) * 3 * 4)
    ofs_texcoords = align(ofs_positions + len(positions) * 3 * 4)
    ofs_normals = align(ofs_texcoords + len(positions) * 2 * 4)
    ofs_comment = align(ofs_normals + len(positions) * 3 * 4)
    filesize = align(ofs_comment + len(comment))

    header = struct.pack(
        "<16s27I",
        b"INTERQUAKEMODEL\0",
        2,
        filesize,
        0,
        len(text),
        ofs_text,
        len(mesh_rows),
        ofs_meshes,
        num_vertexarrays,
        len(positions),
        ofs_vertexarrays,
        len(triangles),
        ofs_triangles,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        len(comment),
        ofs_comment,
        0,
        0,
    )
    vertex_arrays = b"".join(
        (
            struct.pack("<5I", 0, 0, 7, 3, ofs_positions),
            struct.pack("<5I", 1, 0, 7, 2, ofs_texcoords),
            struct.pack("<5I", 2, 0, 7, 3, ofs_normals),
        )
    )
    blob = bytearray(filesize)
    chunks = [
        (0, header),
        (ofs_text, text),
        (ofs_meshes, b"".join(struct.pack("<6I", *row) for row in mesh_rows)),
        (ofs_vertexarrays, vertex_arrays),
        (ofs_triangles, b"".join(struct.pack("<3I", *tri) for tri in triangles)),
        (ofs_positions, b"".join(struct.pack("<3f", *point) for point in positions)),
        (ofs_texcoords, b"".join(struct.pack("<2f", *uv) for uv in texcoords)),
        (ofs_normals, b"".join(struct.pack("<3f", *normal) for normal in normals)),
        (ofs_comment, comment),
    ]
    for offset, data in chunks:
        blob[offset : offset + len(data)] = data
    path.write_bytes(blob)


def font(size: int) -> ImageFont.ImageFont:
    for candidate in ("C:/Windows/Fonts/segoeuib.ttf", "C:/Windows/Fonts/segoeui.ttf", "C:/Windows/Fonts/arial.ttf"):
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def write_textures() -> None:
    for material, spec in MATERIALS.items():
        image = Image.new("RGB", (256, 256), spec["color"])
        draw = ImageDraw.Draw(image)
        if material == "crate_iron":
            for x in range(0, 256, 32):
                draw.line((x, 0, x, 255), fill=(19, 24, 25), width=3)
            for y in range(0, 256, 32):
                draw.line((0, y, 255, y), fill=(61, 70, 70), width=2)
            for x in range(20, 256, 54):
                draw.ellipse((x, 20, x + 18, 38), fill=(108, 116, 112), outline=(8, 12, 12))
        elif material == "hash_panels":
            for i in range(0, 256, 18):
                draw.line((0, i, 255, i + 38), fill=(99, 118, 112), width=2)
            for inset in (18, 42, 66):
                draw.rectangle((inset, inset, 256 - inset, 256 - inset), outline=(38, 49, 48), width=3)
        elif material == "rtc_glow":
            image = Image.new("RGB", (256, 256), (8, 14, 16))
            draw = ImageDraw.Draw(image)
            for radius, color in ((104, (22, 174, 190)), (72, (42, 224, 226)), (38, (255, 144, 38))):
                draw.ellipse((128 - radius, 128 - radius, 128 + radius, 128 + radius), outline=color, width=7)
            draw.text((61, 106), "HASH", fill=(206, 255, 242), font=font(34))
        elif material == "warning_stripe":
            image = Image.new("RGB", (256, 256), (18, 18, 16))
            draw = ImageDraw.Draw(image)
            for x in range(-256, 512, 44):
                draw.polygon([(x, 0), (x + 22, 0), (x + 278, 256), (x + 256, 256)], fill=(236, 139, 32))
            draw.rectangle((18, 18, 238, 238), outline=(255, 214, 88), width=5)
        image.save(OUT / spec["texture"])


def write_material_file(path: Path) -> None:
    lines: list[str] = []
    for material, spec in MATERIALS.items():
        kd = spec["kd"]
        lines.extend((f"newmtl {material}", f"Kd {kd[0]:.3f} {kd[1]:.3f} {kd[2]:.3f}", f"map_Kd {spec['texture']}", ""))
    path.write_text("\n".join(lines), encoding="ascii")


def add_face_panel(mesh: ObjBuilder, axis: str, sign: int, center: float) -> None:
    if axis == "y":
        mesh.add_box((0.0, sign * 0.581, center), (0.60, 0.035, 0.26), "rtc_glow")
        mesh.add_box((-0.44, sign * 0.60, center), (0.18, 0.045, 0.34), "warning_stripe")
        mesh.add_box((0.44, sign * 0.60, center), (0.18, 0.045, 0.34), "warning_stripe")
    else:
        mesh.add_box((sign * 0.581, 0.0, center), (0.035, 0.60, 0.26), "rtc_glow")
        mesh.add_box((sign * 0.60, -0.44, center), (0.045, 0.18, 0.34), "warning_stripe")
        mesh.add_box((sign * 0.60, 0.44, center), (0.045, 0.18, 0.34), "warning_stripe")


def build_mesh() -> ObjBuilder:
    mesh = ObjBuilder()
    mesh.add_box((0.0, 0.0, 0.48), (1.04, 1.04, 0.82), "hash_panels")

    for x in (-0.59, 0.59):
        for y in (-0.59, 0.59):
            mesh.add_box((x, y, 0.48), (0.11, 0.11, 0.98), "crate_iron")
    for z in (0.02, 0.94):
        mesh.add_box((0.0, -0.59, z), (1.28, 0.12, 0.12), "crate_iron")
        mesh.add_box((0.0, 0.59, z), (1.28, 0.12, 0.12), "crate_iron")
        mesh.add_box((-0.59, 0.0, z), (0.12, 1.28, 0.12), "crate_iron")
        mesh.add_box((0.59, 0.0, z), (0.12, 1.28, 0.12), "crate_iron")

    for sign in (-1, 1):
        add_face_panel(mesh, "y", sign, 0.52)
        add_face_panel(mesh, "x", sign, 0.52)

    mesh.add_box((0.0, 0.0, 0.96), (0.70, 0.70, 0.08), "warning_stripe")
    mesh.add_box((0.0, 0.0, 1.03), (0.48, 0.48, 0.08), "rtc_glow")
    mesh.add_cylinder((0.0, 0.0, 1.13), 0.23, 0.10, 16, "crate_iron", "rtc_glow", phase=math.pi / 16)
    mesh.add_box((0.0, 0.0, -0.03), (0.86, 0.86, 0.08), "crate_iron")
    for angle in (math.pi / 4, math.pi * 3 / 4, math.pi * 5 / 4, math.pi * 7 / 4):
        mesh.add_box((math.cos(angle) * 0.35, math.sin(angle) * 0.35, 1.16), (0.09, 0.09, 0.10), "warning_stripe")
    return mesh


def write_skin() -> None:
    lines = [f"{material},models/props/{PROP_NAME}/{Path(spec['texture']).stem}" for material, spec in MATERIALS.items()]
    SKIN_FILE.write_text("\n".join(lines) + "\n", encoding="ascii")


def write_preview() -> None:
    image = Image.new("RGB", (1280, 720), (17, 22, 24))
    draw = ImageDraw.Draw(image)
    for y in range(410, 720, 30):
        draw.line((0, y, 1280, y - 150), fill=(30, 39, 41), width=1)
    cx, cy = 500, 390
    draw.polygon([(cx - 210, cy - 45), (cx + 70, cy - 110), (cx + 226, cy - 18), (cx - 42, cy + 62)], fill=(84, 99, 94), outline=(160, 172, 160))
    draw.polygon([(cx - 210, cy - 45), (cx - 42, cy + 62), (cx - 42, cy + 250), (cx - 210, cy + 132)], fill=(55, 66, 64), outline=(133, 146, 140))
    draw.polygon([(cx - 42, cy + 62), (cx + 226, cy - 18), (cx + 226, cy + 158), (cx - 42, cy + 250)], fill=(73, 86, 82), outline=(133, 146, 140))
    for x0, y0, x1, y1 in ((cx - 188, cy + 8, cx - 68, cy + 86), (cx + 38, cy + 62, cx + 178, cy + 126)):
        draw.rounded_rectangle((x0, y0, x1, y1), radius=6, fill=(20, 177, 188), outline=(218, 255, 245), width=3)
    for pts in (
        [(cx - 190, cy - 35), (cx - 135, cy - 49), (cx - 86, cy - 31), (cx - 142, cy - 16)],
        [(cx + 79, cy - 98), (cx + 133, cy - 70), (cx + 91, cy - 56), (cx + 38, cy - 83)],
        [(cx + 139, cy + 132), (cx + 203, cy + 108), (cx + 203, cy + 153), (cx + 138, cy + 174)],
    ):
        draw.polygon(pts, fill=(232, 137, 32), outline=(255, 217, 96))
    draw.line((cx - 203, cy - 43, cx - 36, cy + 67), fill=(32, 39, 40), width=16)
    draw.line((cx + 70, cy - 105, cx + 225, cy - 15), fill=(32, 39, 40), width=16)
    draw.line((cx - 42, cy + 64, cx - 42, cy + 250), fill=(32, 39, 40), width=16)
    draw.line((cx + 224, cy - 14, cx + 224, cy + 158), fill=(32, 39, 40), width=16)
    draw.text((cx - 44, cy - 74), "HASH", fill=(215, 255, 241), font=font(32))

    draw.text((760, 104), "RustChain", fill=(232, 197, 110), font=font(48))
    draw.text((760, 160), "Hash Crate Prop", fill=(187, 222, 220), font=font(32))
    draw.text((760, 212), "Original low-poly IQM model", fill=(153, 166, 166), font=font(24))
    draw.text((760, 246), "Bounty #14015 - hash crate item", fill=(153, 166, 166), font=font(24))

    swatches = [
        ("iron frame", MATERIALS["crate_iron"]["color"]),
        ("crate panels", MATERIALS["hash_panels"]["color"]),
        ("hash glow", MATERIALS["rtc_glow"]["color"]),
        ("warning plates", MATERIALS["warning_stripe"]["color"]),
    ]
    for i, (label, color) in enumerate(swatches):
        y = 330 + i * 54
        draw.rectangle((768, y, 832, y + 34), fill=color, outline=(220, 230, 226))
        draw.text((850, y + 2), label, fill=(212, 222, 222), font=font(24))
    image.save(PREVIEW_FILE)


def generate() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    write_textures()
    write_material_file(SOURCE_MTL_FILE)
    mesh = build_mesh()
    mesh.write(SOURCE_OBJ_FILE, SOURCE_MTL_FILE.name)
    write_iqm_direct(MODEL_FILE, mesh)
    write_skin()
    write_preview()
    (OUT / "README.md").write_text(README_TEXT, encoding="utf-8")
    (OUT / "LICENSE").write_text(LICENSE_TEXT, encoding="utf-8")


if __name__ == "__main__":
    generate()
    print(f"Wrote {PROP_NAME} prop package to {OUT}")
