"""Generate the RustChain RTC Token Pickup prop package.

The output is an original low-poly IQM prop for bounty #14015:
pk3_build/models/props/rustchain_rtc_token_pickup/.
"""

from __future__ import annotations

import math
import struct
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
PROP_NAME = "rustchain_rtc_token_pickup"
OUT = ROOT / "pk3_build" / "models" / "props" / PROP_NAME

MODEL_FILE = OUT / f"{PROP_NAME}.iqm"
SKIN_FILE = OUT / f"{PROP_NAME}_0.skin"
SOURCE_OBJ_FILE = OUT / f"{PROP_NAME}_source.obj"
SOURCE_MTL_FILE = OUT / f"{PROP_NAME}_source.mtl"
PREVIEW_FILE = OUT / f"{PROP_NAME}_preview.png"

MATERIALS = {
    "token_gold": {
        "texture": "rtc_token_pickup_gold.tga",
        "color": (232, 171, 55),
        "kd": (0.90, 0.62, 0.18),
    },
    "token_edge": {
        "texture": "rtc_token_pickup_edge.tga",
        "color": (96, 72, 35),
        "kd": (0.42, 0.30, 0.12),
    },
    "pickup_glow": {
        "texture": "rtc_token_pickup_glow.tga",
        "color": (255, 119, 34),
        "kd": (1.00, 0.44, 0.10),
    },
    "pickup_base": {
        "texture": "rtc_token_pickup_base.tga",
        "color": (31, 38, 42),
        "kd": (0.16, 0.19, 0.21),
    },
}

README_TEXT = """# RustChain RTC Token Pickup prop

Original low-poly set-dressing prop for the Xonotic RustChain Arena prop bounty #14015:
https://github.com/Scottcjn/rustchain-bounties/issues/14015

## Package

| File | Purpose |
| --- | --- |
| `rustchain_rtc_token_pickup.iqm` | Static IQM model written directly from deterministic procedural geometry |
| `rustchain_rtc_token_pickup_0.skin` | DarkPlaces/Xonotic material-to-texture mapping |
| `rtc_token_pickup_gold.tga` | 256x256 RTC coin face texture |
| `rtc_token_pickup_edge.tga` | 256x256 darker coin rim texture |
| `rtc_token_pickup_glow.tga` | 256x256 orange/cyan pickup glow texture |
| `rtc_token_pickup_base.tga` | 256x256 dark metal pedestal texture |
| `rustchain_rtc_token_pickup_preview.png` | Preview render and texture swatches |
| `rustchain_rtc_token_pickup_source.obj` | Reproducible source mesh generated by the Python script |
| `rustchain_rtc_token_pickup_source.mtl` | Source material table for the generated OBJ mesh |

## Design

The model implements the **RTC token pickup** wishlist item. It is a compact
pickup-style arena prop with:

- floating RTC coin disk
- dark metal pedestal
- rotating-style lower glow ring
- four orange pickup pylons
- cyan/gold accent rails

The geometry is procedural and original. It does not embed external meshes,
samples, textures, or AI-generated model files.

## Regeneration

From the repository root:

```powershell
python tools/generate_rustchain_rtc_token_pickup_prop.py
```

The script writes the OBJ/MTL source, TGA textures, PNG preview, README,
LICENSE, skin file, and static IQM v2 model. It does not require Blender or
the bundled IQM executable.
"""

LICENSE_TEXT = """RustChain RTC Token Pickup prop

Copyright 2026

This model, texture pack, preview image, and deterministic procedural source
are licensed under the Creative Commons Attribution-ShareAlike 4.0
International License (CC-BY-SA-4.0).

You are free to share and adapt the material for any purpose, even
commercially, provided attribution is given and adaptations are distributed
under the same license.

License summary and legal code:
https://creativecommons.org/licenses/by-sa/4.0/
"""


class ObjBuilder:
    def __init__(self) -> None:
        self.vertices: list[tuple[float, float, float]] = []
        self.uvs: list[tuple[float, float]] = []
        self.faces: list[tuple[str, tuple[tuple[int, int], tuple[int, int], tuple[int, int]]]] = []

    def _add_vertex(self, point: tuple[float, float, float], uv: tuple[float, float]) -> tuple[int, int]:
        self.vertices.append(point)
        self.uvs.append(uv)
        return len(self.vertices), len(self.uvs)

    def add_tri(
        self,
        material: str,
        points: tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]],
        uvs: tuple[tuple[float, float], tuple[float, float], tuple[float, float]] = ((0.0, 0.0), (1.0, 0.0), (0.5, 1.0)),
    ) -> None:
        self.faces.append((material, tuple(self._add_vertex(point, uv) for point, uv in zip(points, uvs))))

    def add_quad(
        self,
        material: str,
        points: tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]],
    ) -> None:
        uvs = ((0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0))
        self.add_tri(material, (points[0], points[1], points[2]), (uvs[0], uvs[1], uvs[2]))
        self.add_tri(material, (points[0], points[2], points[3]), (uvs[0], uvs[2], uvs[3]))

    def add_box(self, center: tuple[float, float, float], size: tuple[float, float, float], material: str) -> None:
        cx, cy, cz = center
        sx, sy, sz = (s / 2.0 for s in size)
        x0, x1 = cx - sx, cx + sx
        y0, y1 = cy - sy, cy + sy
        z0, z1 = cz - sz, cz + sz
        self.add_quad(material, ((x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1)))
        self.add_quad(material, ((x1, y0, z0), (x0, y0, z0), (x0, y0, z1), (x1, y0, z1)))
        self.add_quad(material, ((x1, y1, z0), (x1, y0, z0), (x1, y0, z1), (x1, y1, z1)))
        self.add_quad(material, ((x0, y0, z0), (x0, y1, z0), (x0, y1, z1), (x0, y0, z1)))
        self.add_quad(material, ((x0, y0, z1), (x0, y1, z1), (x1, y1, z1), (x1, y0, z1)))
        self.add_quad(material, ((x0, y1, z0), (x0, y0, z0), (x1, y0, z0), (x1, y1, z0)))

    def add_cylinder(
        self,
        center: tuple[float, float, float],
        radius: float,
        height: float,
        segments: int,
        side_material: str,
        cap_material: str | None = None,
        phase: float = 0.0,
    ) -> None:
        cx, cy, cz = center
        z0, z1 = cz - height / 2.0, cz + height / 2.0
        cap = cap_material or side_material
        bottom_center = (cx, cy, z0)
        top_center = (cx, cy, z1)
        ring: list[tuple[float, float, float]] = []
        for i in range(segments):
            a = phase + (math.tau * i / segments)
            ring.append((cx + math.cos(a) * radius, cy + math.sin(a) * radius, 0.0))
        for i in range(segments):
            p0 = ring[i]
            p1 = ring[(i + 1) % segments]
            bottom0 = (p0[0], p0[1], z0)
            bottom1 = (p1[0], p1[1], z0)
            top0 = (p0[0], p0[1], z1)
            top1 = (p1[0], p1[1], z1)
            u0 = i / segments
            u1 = (i + 1) / segments
            self.add_tri(side_material, (bottom0, bottom1, top1), ((u0, 0.0), (u1, 0.0), (u1, 1.0)))
            self.add_tri(side_material, (bottom0, top1, top0), ((u0, 0.0), (u1, 1.0), (u0, 1.0)))
            self.add_tri(cap, (top_center, top0, top1), ((0.5, 0.5), (0.0, 1.0), (1.0, 1.0)))
            self.add_tri(cap, (bottom_center, bottom1, bottom0), ((0.5, 0.5), (1.0, 0.0), (0.0, 0.0)))

    def write(self, path: Path, mtl_name: str) -> None:
        lines = [f"mtllib {mtl_name}", f"o {PROP_NAME}"]
        lines.extend(f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in self.vertices)
        lines.extend(f"vt {u:.6f} {v:.6f}" for u, v in self.uvs)
        current_material = None
        for material, face in self.faces:
            if material != current_material:
                lines.append(f"usemtl {material}")
                current_material = material
            verts = " ".join(f"{vi}/{ti}" for vi, ti in face)
            lines.append(f"f {verts}")
        path.write_text("\n".join(lines) + "\n", encoding="ascii")


def align(value: int, boundary: int = 4) -> int:
    return (value + boundary - 1) // boundary * boundary


def normal_for(points: tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]]) -> tuple[float, float, float]:
    ax, ay, az = points[0]
    bx, by, bz = points[1]
    cx, cy, cz = points[2]
    ux, uy, uz = bx - ax, by - ay, bz - az
    vx, vy, vz = cx - ax, cy - ay, cz - az
    nx = uy * vz - uz * vy
    ny = uz * vx - ux * vz
    nz = ux * vy - uy * vx
    length = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
    return nx / length, ny / length, nz / length


def write_iqm_direct(path: Path, mesh: ObjBuilder) -> None:
    strings = ["", PROP_NAME, *MATERIALS.keys()]
    offsets: dict[str, int] = {}
    cursor = 0
    text_parts: list[bytes] = []
    for item in strings:
        offsets[item] = cursor
        encoded = item.encode("ascii") + b"\0"
        text_parts.append(encoded)
        cursor += len(encoded)
    text = b"".join(text_parts)

    positions: list[tuple[float, float, float]] = []
    texcoords: list[tuple[float, float]] = []
    normals: list[tuple[float, float, float]] = []
    triangles: list[tuple[int, int, int]] = []
    mesh_rows: list[tuple[int, int, int, int, int, int]] = []
    for material in MATERIALS:
        first_vertex = len(positions)
        first_triangle = len(triangles)
        for face_material, face in mesh.faces:
            if face_material != material:
                continue
            points = tuple(mesh.vertices[vertex_index - 1] for vertex_index, _ in face)
            uvs = tuple(mesh.uvs[uv_index - 1] for _, uv_index in face)
            normal = normal_for(points)
            tri = []
            for point, uv in zip(points, uvs):
                positions.append(point)
                texcoords.append(uv)
                normals.append(normal)
                tri.append(len(positions) - 1)
            triangles.append(tuple(tri))
        mesh_rows.append((offsets[PROP_NAME], offsets[material], first_vertex, len(positions) - first_vertex, first_triangle, len(triangles) - first_triangle))

    comment = b"Deterministic Python-generated static IQM for RustChain RTC token pickup.\0"
    header_size = 16 + 27 * 4
    num_vertexarrays = 3
    ofs_text = align(header_size)
    ofs_meshes = align(ofs_text + len(text))
    ofs_vertexarrays = align(ofs_meshes + len(mesh_rows) * 6 * 4)
    ofs_triangles = align(ofs_vertexarrays + num_vertexarrays * 5 * 4)
    ofs_positions = align(ofs_triangles + len(triangles) * 3 * 4)
    ofs_texcoords = align(ofs_positions + len(positions) * 3 * 4)
    ofs_normals = align(ofs_texcoords + len(positions) * 2 * 4)
    ofs_comment = align(ofs_normals + len(positions) * 3 * 4)
    filesize = align(ofs_comment + len(comment))

    header = struct.pack(
        "<16s27I",
        b"INTERQUAKEMODEL\0",
        2,
        filesize,
        0,
        len(text),
        ofs_text,
        len(mesh_rows),
        ofs_meshes,
        num_vertexarrays,
        len(positions),
        ofs_vertexarrays,
        len(triangles),
        ofs_triangles,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        len(comment),
        ofs_comment,
        0,
        0,
    )
    vertex_arrays = b"".join(
        (
            struct.pack("<5I", 0, 0, 7, 3, ofs_positions),
            struct.pack("<5I", 1, 0, 7, 2, ofs_texcoords),
            struct.pack("<5I", 2, 0, 7, 3, ofs_normals),
        )
    )
    blob = bytearray(filesize)
    chunks = [
        (0, header),
        (ofs_text, text),
        (ofs_meshes, b"".join(struct.pack("<6I", *row) for row in mesh_rows)),
        (ofs_vertexarrays, vertex_arrays),
        (ofs_triangles, b"".join(struct.pack("<3I", *tri) for tri in triangles)),
        (ofs_positions, b"".join(struct.pack("<3f", *point) for point in positions)),
        (ofs_texcoords, b"".join(struct.pack("<2f", *uv) for uv in texcoords)),
        (ofs_normals, b"".join(struct.pack("<3f", *normal) for normal in normals)),
        (ofs_comment, comment),
    ]
    for offset, data in chunks:
        blob[offset : offset + len(data)] = data
    path.write_bytes(blob)


def font(size: int) -> ImageFont.ImageFont:
    for candidate in ("C:/Windows/Fonts/segoeuib.ttf", "C:/Windows/Fonts/segoeui.ttf", "C:/Windows/Fonts/arial.ttf"):
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def write_textures() -> None:
    for material, spec in MATERIALS.items():
        image = Image.new("RGB", (256, 256), spec["color"])
        draw = ImageDraw.Draw(image)
        if material == "token_gold":
            for i in range(0, 256, 14):
                draw.line((0, i, 255, i + 44), fill=(255, 214 - i % 40, 94), width=3)
            draw.ellipse((34, 34, 222, 222), outline=(255, 238, 154), width=10)
            draw.ellipse((58, 58, 198, 198), outline=(124, 74, 20), width=4)
            draw.text((82, 103), "RTC", fill=(72, 40, 12), font=font(38))
        elif material == "token_edge":
            for x in range(0, 256, 18):
                draw.rectangle((x, 0, x + 8, 255), fill=(128, 87, 31))
            for y in range(16, 256, 32):
                draw.line((0, y, 255, y), fill=(58, 39, 20), width=3)
        elif material == "pickup_glow":
            image = Image.new("RGB", (256, 256), (9, 11, 14))
            draw = ImageDraw.Draw(image)
            for radius, color in ((102, (255, 96, 24)), (76, (255, 174, 56)), (48, (40, 210, 230))):
                draw.ellipse((128 - radius, 128 - radius, 128 + radius, 128 + radius), outline=color, width=8)
            for a in range(0, 360, 30):
                x = 128 + math.cos(math.radians(a)) * 104
                y = 128 + math.sin(math.radians(a)) * 104
                draw.line((128, 128, x, y), fill=(33, 176, 190), width=2)
        elif material == "pickup_base":
            for x in range(0, 256, 32):
                draw.line((x, 0, x, 255), fill=(48, 58, 62), width=2)
            for y in range(0, 256, 32):
                draw.line((0, y, 255, y), fill=(17, 22, 25), width=2)
            for i in range(9):
                draw.rectangle((22, 20 + i * 25, 234, 32 + i * 25), outline=(78, 91, 92), width=1)
        image.save(OUT / spec["texture"])


def write_material_file(path: Path) -> None:
    lines: list[str] = []
    for material, spec in MATERIALS.items():
        kd = spec["kd"]
        lines.extend((f"newmtl {material}", f"Kd {kd[0]:.3f} {kd[1]:.3f} {kd[2]:.3f}", f"map_Kd {spec['texture']}", ""))
    path.write_text("\n".join(lines), encoding="ascii")


def build_mesh() -> ObjBuilder:
    mesh = ObjBuilder()
    mesh.add_cylinder((0.0, 0.0, 0.08), 0.48, 0.16, 16, "pickup_base", "pickup_base", phase=math.pi / 16)
    mesh.add_cylinder((0.0, 0.0, 0.27), 0.34, 0.14, 16, "pickup_base", "token_edge", phase=math.pi / 16)
    mesh.add_cylinder((0.0, 0.0, 0.50), 0.86, 0.035, 32, "pickup_glow", "pickup_glow")
    mesh.add_cylinder((0.0, 0.0, 0.83), 0.62, 0.10, 32, "token_edge", "token_gold")
    mesh.add_cylinder((0.0, 0.0, 0.91), 0.46, 0.035, 32, "token_gold", "token_gold")
    mesh.add_cylinder((0.0, 0.0, 0.98), 0.30, 0.025, 24, "pickup_glow", "pickup_glow")
    for a in (0, math.pi / 2, math.pi, math.pi * 3 / 2):
        x = math.cos(a) * 0.64
        y = math.sin(a) * 0.64
        rail_x = 0.09 if abs(math.cos(a)) < 0.1 else 0.035
        rail_y = 0.09 if abs(math.sin(a)) < 0.1 else 0.035
        mesh.add_box((x, y, 0.48), (rail_x, rail_y, 0.55), "pickup_glow")
    for a in (math.pi / 4, math.pi * 3 / 4, math.pi * 5 / 4, math.pi * 7 / 4):
        x = math.cos(a) * 0.44
        y = math.sin(a) * 0.44
        mesh.add_box((x, y, 0.31), (0.10, 0.10, 0.25), "token_edge")
    return mesh


def write_skin() -> None:
    lines = [f"{material},models/props/{PROP_NAME}/{Path(spec['texture']).stem}" for material, spec in MATERIALS.items()]
    SKIN_FILE.write_text("\n".join(lines) + "\n", encoding="ascii")


def write_preview() -> None:
    image = Image.new("RGB", (1280, 720), (18, 23, 26))
    draw = ImageDraw.Draw(image)
    for y in range(410, 720, 28):
        draw.line((0, y, 1280, y - 170), fill=(29, 38, 41), width=1)
    for x in range(-180, 1420, 80):
        draw.line((x, 720, x + 520, 360), fill=(24, 33, 36), width=1)

    cx, cy = 505, 425
    draw.ellipse((cx - 235, cy + 55, cx + 235, cy + 115), outline=(255, 119, 34), width=7)
    draw.ellipse((cx - 170, cy + 72, cx + 170, cy + 100), outline=(36, 209, 229), width=4)
    draw.polygon([(cx - 92, cy + 135), (cx + 92, cy + 135), (cx + 70, cy + 190), (cx - 70, cy + 190)], fill=(39, 46, 49), outline=(120, 134, 130))
    for x, y in ((cx - 188, cy + 58), (cx + 188, cy + 58), (cx, cy - 42), (cx, cy + 158)):
        draw.rounded_rectangle((x - 13, y - 58, x + 13, y + 66), radius=8, fill=(255, 113, 32), outline=(255, 214, 98), width=2)
    draw.ellipse((cx - 140, cy - 170, cx + 140, cy + 70), fill=(226, 160, 44), outline=(255, 230, 126), width=9)
    draw.ellipse((cx - 102, cy - 134, cx + 102, cy + 34), outline=(96, 56, 18), width=6)
    draw.text((cx - 66, cy - 65), "RTC", fill=(72, 40, 12), font=font(52))
    draw.ellipse((cx - 74, cy - 195, cx + 74, cy - 132), fill=(255, 111, 34), outline=(255, 226, 102), width=4)

    draw.text((760, 104), "RustChain RTC", fill=(241, 206, 126), font=font(48))
    draw.text((760, 160), "Token Pickup Prop", fill=(186, 218, 220), font=font(30))
    draw.text((760, 212), "Original low-poly IQM model", fill=(150, 164, 166), font=font(24))
    draw.text((760, 246), "Bounty #14015 - 7 RTC prop lane", fill=(150, 164, 166), font=font(24))

    swatches = [
        ("token gold", MATERIALS["token_gold"]["color"]),
        ("coin edge", MATERIALS["token_edge"]["color"]),
        ("pickup glow", MATERIALS["pickup_glow"]["color"]),
        ("dark base", MATERIALS["pickup_base"]["color"]),
    ]
    for i, (label, color) in enumerate(swatches):
        y = 330 + i * 54
        draw.rectangle((768, y, 832, y + 34), fill=color, outline=(220, 230, 226))
        draw.text((850, y + 2), label, fill=(212, 222, 222), font=font(24))
    image.save(PREVIEW_FILE)


def generate() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    write_textures()
    write_material_file(SOURCE_MTL_FILE)
    mesh = build_mesh()
    mesh.write(SOURCE_OBJ_FILE, SOURCE_MTL_FILE.name)
    write_iqm_direct(MODEL_FILE, mesh)
    write_skin()
    write_preview()
    (OUT / "README.md").write_text(README_TEXT, encoding="utf-8")
    (OUT / "LICENSE").write_text(LICENSE_TEXT, encoding="utf-8")


if __name__ == "__main__":
    generate()
    print(f"Wrote {PROP_NAME} prop package to {OUT}")
