"""Generate the RustChain vintage PowerPC-style tower prop package.

The output is an original low-poly static prop for bounty #14015:
pk3_build/models/props/rustchain_vintage_powerpc_tower/.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
PROP_NAME = "rustchain_vintage_powerpc_tower"
OUT = ROOT / "pk3_build" / "models" / "props" / PROP_NAME
TEXTURES = OUT / "textures"

OBJ_FILE = OUT / f"{PROP_NAME}.obj"
MTL_FILE = OUT / f"{PROP_NAME}.mtl"
SKIN_FILE = OUT / f"{PROP_NAME}.skin"
PREVIEW_FILE = OUT / "preview.png"
IQM_FILE = OUT / f"{PROP_NAME}.iqm"

MATERIALS = {
    "powerpc_case": {
        "texture": "textures/powerpc_case.tga",
        "color": (190, 181, 154),
        "kd": (0.72, 0.68, 0.58),
    },
    "powerpc_dark": {
        "texture": "textures/powerpc_dark.tga",
        "color": (34, 36, 38),
        "kd": (0.12, 0.13, 0.14),
    },
    "powerpc_glow": {
        "texture": "textures/powerpc_glow.tga",
        "color": (31, 216, 224),
        "kd": (0.05, 0.84, 0.88),
    },
    "powerpc_label": {
        "texture": "textures/powerpc_label.tga",
        "color": (220, 152, 52),
        "kd": (0.82, 0.50, 0.18),
    },
}

README_TEXT = """# RustChain Vintage PowerPC Tower prop

Original low-poly set-dressing prop for the Xonotic RustChain Arena prop bounty #14015:
https://github.com/Scottcjn/rustchain-bounties/issues/14015

## Package

| File | Purpose |
| --- | --- |
| `rustchain_vintage_powerpc_tower.iqm` | Static IQM model for Xonotic/DarkPlaces |
| `rustchain_vintage_powerpc_tower.obj` | Editable source mesh generated by the Python script |
| `rustchain_vintage_powerpc_tower.mtl` | Source material table for the OBJ |
| `rustchain_vintage_powerpc_tower.skin` | Xonotic material-to-texture mapping |
| `textures/*.tga` | 256x256 power-of-two texture set |
| `preview.png` | Generated 1280x720 preview sheet |
| `README.md` | Integration and design notes |
| `LICENSE` | CC-BY-SA-4.0 / GPL-compatible asset license |

## Design

This implements the **Vintage PowerPC / retro tower** wishlist item. The prop is
a beige late-1990s tower silhouette with stacked optical/floppy bays, vertical
front vents, a small cyan RTC activity window, colored side badge stripes, rear
port hints, and chunky pedestal feet. It is meant for antiquity-vault corners,
server rooms, spawn alcoves, and map-side storytelling around old silicon.

The geometry and textures are original procedural assets. No external mesh,
photo texture, AI-generated model file, or trademarked logo is embedded.

## Regeneration

From the repository root:

```powershell
python tools/generate_rustchain_vintage_powerpc_tower_prop.py
```

The script writes the OBJ/MTL source, TGA textures, PNG preview, README,
LICENSE, and skin file. The committed IQM was converted from the generated OBJ
with the repository IQM compiler rebuilt locally for the current Linux runtime:

```bash
cd source/iqm
g++ -O3 -fomit-frame-pointer -Wall -fsigned-char -o /tmp/iqm-local iqm.cpp
cd ../..
/tmp/iqm-local pk3_build/models/props/rustchain_vintage_powerpc_tower/rustchain_vintage_powerpc_tower.iqm \
  pk3_build/models/props/rustchain_vintage_powerpc_tower/rustchain_vintage_powerpc_tower.obj
```

## Placement

Suggested use: low-cover set dressing against walls, behind glass, or inside an
antiquity vault. The model is static and low-poly; mappers can scale it to fit
server-room corridors or museum-style displays.
"""

LICENSE_TEXT = """RustChain Vintage PowerPC Tower prop

Copyright 2026

This model, texture pack, preview image, and deterministic procedural source
are licensed under the Creative Commons Attribution-ShareAlike 4.0
International License (CC-BY-SA-4.0).

You are free to share and adapt the material for any purpose, even
commercially, provided attribution is given and adaptations are distributed
under the same license.

License summary and legal code:
https://creativecommons.org/licenses/by-sa/4.0/
"""


class ObjMesh:
    def __init__(self) -> None:
        self.vertices: list[tuple[float, float, float]] = []
        self.uvs: list[tuple[float, float]] = []
        self.faces: list[tuple[str, tuple[int, int, int, int], tuple[int, int, int, int]]] = []

    def _add_vertex(self, xyz: tuple[float, float, float], uv: tuple[float, float]) -> tuple[int, int]:
        self.vertices.append(xyz)
        self.uvs.append(uv)
        idx = len(self.vertices)
        return idx, idx

    def add_quad(self, material: str, points: list[tuple[float, float, float]]) -> None:
        uv_points = [(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)]
        pairs = [self._add_vertex(point, uv) for point, uv in zip(points, uv_points)]
        self.faces.append((material, tuple(v for v, _ in pairs), tuple(t for _, t in pairs)))

    def add_box(
        self,
        center: tuple[float, float, float],
        size: tuple[float, float, float],
        material: str,
    ) -> None:
        cx, cy, cz = center
        sx, sy, sz = (axis / 2.0 for axis in size)
        x0, x1 = cx - sx, cx + sx
        y0, y1 = cy - sy, cy + sy
        z0, z1 = cz - sz, cz + sz
        self.add_quad(material, [(x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1)])
        self.add_quad(material, [(x1, y1, z0), (x0, y1, z0), (x0, y1, z1), (x1, y1, z1)])
        self.add_quad(material, [(x0, y1, z0), (x0, y0, z0), (x0, y0, z1), (x0, y1, z1)])
        self.add_quad(material, [(x1, y0, z0), (x1, y1, z0), (x1, y1, z1), (x1, y0, z1)])
        self.add_quad(material, [(x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)])
        self.add_quad(material, [(x0, y1, z0), (x1, y1, z0), (x1, y0, z0), (x0, y0, z0)])

    def write_obj(self, path: Path) -> None:
        lines = [
            f"# {PROP_NAME} - deterministic source mesh",
            f"mtllib {MTL_FILE.name}",
            "o rustchain_vintage_powerpc_tower",
        ]
        for vertex in self.vertices:
            lines.append("v {:.4f} {:.4f} {:.4f}".format(*vertex))
        for uv in self.uvs:
            lines.append("vt {:.4f} {:.4f}".format(*uv))
        current_material = ""
        for material, verts, texcoords in self.faces:
            if material != current_material:
                lines.append(f"usemtl {material}")
                current_material = material
            refs = [f"{v}/{t}" for v, t in zip(verts, texcoords)]
            lines.append("f " + " ".join(refs))
        path.write_text("\n".join(lines) + "\n", encoding="ascii")


def font(size: int) -> ImageFont.ImageFont:
    for name in ("DejaVuSans.ttf", "arial.ttf"):
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            continue
    return ImageFont.load_default()


def write_texture(name: str, base: tuple[int, int, int], accent: tuple[int, int, int]) -> None:
    image = Image.new("RGB", (256, 256), base)
    draw = ImageDraw.Draw(image)
    if "case" in name:
        for x in range(0, 256, 32):
            draw.line((x, 0, x, 255), fill=tuple(max(0, c - 18) for c in base))
        for y in range(0, 256, 32):
            draw.line((0, y, 255, y), fill=tuple(min(255, c + 12) for c in base))
        draw.rectangle((18, 18, 238, 238), outline=accent, width=3)
    elif "dark" in name:
        for y in range(12, 256, 18):
            draw.rectangle((22, y, 234, y + 7), fill=accent)
    elif "glow" in name:
        for r in range(110, 8, -12):
            shade = tuple(min(255, int(c * (0.28 + r / 130))) for c in accent)
            draw.ellipse((128 - r, 128 - r, 128 + r, 128 + r), outline=shade, width=5)
        draw.text((86, 110), "RTC", fill=(8, 34, 38), font=font(36))
    else:
        colors = [(220, 67, 57), (239, 167, 45), (86, 184, 96), (58, 137, 220)]
        for idx, color in enumerate(colors):
            draw.rectangle((0, idx * 64, 256, idx * 64 + 47), fill=color)
        draw.text((54, 196), "PPC", fill=(30, 28, 24), font=font(36))
    image.save(TEXTURES / name)


def write_textures() -> None:
    write_texture("powerpc_case.tga", (190, 181, 154), (128, 117, 88))
    write_texture("powerpc_dark.tga", (28, 30, 32), (78, 84, 86))
    write_texture("powerpc_glow.tga", (10, 39, 43), (31, 216, 224))
    write_texture("powerpc_label.tga", (220, 152, 52), (255, 232, 142))


def build_mesh() -> ObjMesh:
    mesh = ObjMesh()
    mesh.add_box((0.0, 0.0, 1.45), (1.05, 0.54, 2.80), "powerpc_case")
    mesh.add_box((0.0, -0.31, 1.45), (0.88, 0.07, 2.42), "powerpc_case")
    mesh.add_box((0.0, -0.36, 2.42), (0.62, 0.06, 0.18), "powerpc_dark")
    mesh.add_box((0.0, -0.36, 2.12), (0.62, 0.06, 0.13), "powerpc_dark")
    mesh.add_box((0.0, -0.365, 1.78), (0.42, 0.05, 0.11), "powerpc_dark")
    mesh.add_box((-0.28, -0.37, 1.34), (0.10, 0.05, 0.84), "powerpc_dark")
    mesh.add_box((-0.11, -0.37, 1.34), (0.10, 0.05, 0.84), "powerpc_dark")
    mesh.add_box((0.06, -0.37, 1.34), (0.10, 0.05, 0.84), "powerpc_dark")
    mesh.add_box((0.29, -0.37, 1.43), (0.20, 0.05, 0.26), "powerpc_glow")
    mesh.add_box((0.26, -0.37, 0.94), (0.34, 0.05, 0.12), "powerpc_label")
    mesh.add_box((-0.42, -0.39, 0.20), (0.23, 0.20, 0.16), "powerpc_case")
    mesh.add_box((0.42, -0.39, 0.20), (0.23, 0.20, 0.16), "powerpc_case")
    mesh.add_box((-0.56, 0.0, 1.45), (0.07, 0.48, 2.46), "powerpc_dark")
    mesh.add_box((0.56, 0.0, 1.45), (0.07, 0.48, 2.46), "powerpc_dark")
    mesh.add_box((0.0, 0.31, 1.68), (0.72, 0.07, 1.50), "powerpc_dark")
    mesh.add_box((-0.26, 0.36, 1.98), (0.14, 0.05, 0.12), "powerpc_glow")
    mesh.add_box((0.00, 0.36, 1.98), (0.14, 0.05, 0.12), "powerpc_glow")
    mesh.add_box((0.26, 0.36, 1.98), (0.14, 0.05, 0.12), "powerpc_glow")
    mesh.add_box((0.0, 0.0, 2.92), (0.66, 0.42, 0.16), "powerpc_case")
    mesh.add_box((0.0, -0.02, 3.04), (0.36, 0.20, 0.08), "powerpc_dark")
    return mesh


def write_mtl() -> None:
    lines = ["# Material table for rustchain_vintage_powerpc_tower"]
    for name, material in MATERIALS.items():
        kd = material["kd"]
        lines.extend(
            [
                f"newmtl {name}",
                "Ka 0.000 0.000 0.000",
                "Kd {:.3f} {:.3f} {:.3f}".format(*kd),
                "Ks 0.050 0.050 0.050",
                "Ns 16.0",
                f"map_Kd {material['texture']}",
                "",
            ]
        )
    MTL_FILE.write_text("\n".join(lines), encoding="ascii")


def write_skin() -> None:
    lines = [
        f"{name},models/props/{PROP_NAME}/{material['texture']}"
        for name, material in MATERIALS.items()
    ]
    SKIN_FILE.write_text("\n".join(lines) + "\n", encoding="ascii")


def write_preview() -> None:
    image = Image.new("RGB", (1280, 720), (20, 24, 27))
    draw = ImageDraw.Draw(image)
    draw.rectangle((80, 80, 520, 660), fill=(47, 51, 52), outline=(86, 96, 99), width=4)
    draw.rectangle((185, 100, 415, 640), fill=MATERIALS["powerpc_case"]["color"], outline=(128, 117, 88), width=6)
    draw.rectangle((225, 146, 375, 188), fill=MATERIALS["powerpc_dark"]["color"])
    draw.rectangle((235, 220, 365, 250), fill=MATERIALS["powerpc_dark"]["color"])
    for x in (232, 275, 318):
        draw.rectangle((x, 305, x + 22, 488), fill=MATERIALS["powerpc_dark"]["color"])
    draw.rectangle((335, 360, 392, 420), fill=MATERIALS["powerpc_glow"]["color"])
    draw.text((341, 374), "RTC", fill=(5, 35, 38), font=font(16))
    stripe_y = 530
    for idx, color in enumerate([(220, 67, 57), (239, 167, 45), (86, 184, 96), (58, 137, 220)]):
        draw.rectangle((230 + idx * 36, stripe_y, 258 + idx * 36, stripe_y + 24), fill=color)
    draw.text((620, 112), "RustChain Vintage", fill=(238, 238, 230), font=font(39))
    draw.text((620, 158), "PowerPC Tower", fill=(238, 238, 230), font=font(39))
    draw.text((622, 218), "Original low-poly static IQM prop", fill=(168, 180, 180), font=font(25))
    draw.text((622, 258), "Bounty #14015 - vintage / retro tower slot", fill=(168, 180, 180), font=font(25))
    draw.text((622, 300), "Features", fill=(238, 238, 230), font=font(30))
    for i, line in enumerate(
        [
            "Stacked optical and floppy bays",
            "Vertical front cooling vents",
            "Cyan RTC activity window",
            "Side badge color stripes",
            "Rear port hints and chunky feet",
        ]
    ):
        draw.text((650, 352 + i * 38), "- " + line, fill=(204, 210, 204), font=font(23))
    for i, (name, material) in enumerate(MATERIALS.items()):
        x = 630 + i * 140
        draw.rectangle((x, 580, x + 86, 640), fill=material["color"])
        draw.text((x, 650), name.replace("powerpc_", ""), fill=(190, 198, 196), font=font(18))
    image.save(PREVIEW_FILE)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    TEXTURES.mkdir(parents=True, exist_ok=True)
    write_textures()
    mesh = build_mesh()
    mesh.write_obj(OBJ_FILE)
    write_mtl()
    write_skin()
    write_preview()
    (OUT / "README.md").write_text(README_TEXT, encoding="utf-8")
    (OUT / "LICENSE").write_text(LICENSE_TEXT, encoding="utf-8")
    print(f"Wrote prop source package to {OUT}")
    print(f"Convert OBJ to IQM separately: {IQM_FILE}")


if __name__ == "__main__":
    main()
