#!/usr/bin/env python3
"""
Blender Player Model Export Script for Xonotic/DarkPlaces
Exports rigged character models to IQM format with animations

Usage (from Blender):
    1. Open your rigged character in Blender
    2. Run this script from Text Editor
    OR
    blender model.blend --background --python export_player_model.py -- output.iqm

Requirements:
    - Blender 3.0+
    - Model with armature
    - Animations in NLA strips or actions

Animation naming convention for Xonotic:
    idle, walk, run, jump, crouch, pain, death, shoot
"""

import bpy
import os
import sys

# Xonotic player model animation names
XONOTIC_ANIMS = {
    'idle': {'start': 0, 'end': 30, 'fps': 10, 'loop': True},
    'walk': {'start': 31, 'end': 60, 'fps': 20, 'loop': True},
    'run': {'start': 61, 'end': 80, 'fps': 25, 'loop': True},
    'jump': {'start': 81, 'end': 95, 'fps': 20, 'loop': False},
    'crouch': {'start': 96, 'end': 110, 'fps': 15, 'loop': True},
    'pain': {'start': 111, 'end': 120, 'fps': 20, 'loop': False},
    'death': {'start': 121, 'end': 150, 'fps': 15, 'loop': False},
    'shoot': {'start': 151, 'end': 165, 'fps': 30, 'loop': False},
}

def get_output_path():
    """Get output path from command line or default"""
    if '--' in sys.argv:
        idx = sys.argv.index('--')
        if len(sys.argv) > idx + 1:
            return sys.argv[idx + 1]

    # Default: same name as blend file
    blend_path = bpy.data.filepath
    if blend_path:
        return os.path.splitext(blend_path)[0] + '.iqm'
    return '/tmp/player_model.iqm'

def export_to_obj_frames(output_dir, armature_name=None):
    """Export each animation frame as OBJ for IQM conversion"""
    os.makedirs(output_dir, exist_ok=True)

    # Find armature
    armature = None
    if armature_name:
        armature = bpy.data.objects.get(armature_name)
    else:
        for obj in bpy.context.scene.objects:
            if obj.type == 'ARMATURE':
                armature = obj
                break

    if not armature:
        print("ERROR: No armature found!")
        return []

    # Find mesh
    mesh_obj = None
    for obj in bpy.context.scene.objects:
        if obj.type == 'MESH' and obj.parent == armature:
            mesh_obj = obj
            break

    if not mesh_obj:
        print("ERROR: No mesh parented to armature!")
        return []

    print(f"Exporting: {mesh_obj.name} with armature {armature.name}")

    # Export frames
    exported_files = []
    frame_num = 0

    for anim_name, anim_data in XONOTIC_ANIMS.items():
        print(f"  Animation: {anim_name} (frames {anim_data['start']}-{anim_data['end']})")

        for frame in range(anim_data['start'], anim_data['end'] + 1):
            bpy.context.scene.frame_set(frame)

            # Apply armature modifier
            depsgraph = bpy.context.evaluated_depsgraph_get()
            mesh_eval = mesh_obj.evaluated_get(depsgraph)

            # Export OBJ
            output_file = os.path.join(output_dir, f"frame_{frame_num:04d}.obj")

            # Select only the mesh
            bpy.ops.object.select_all(action='DESELECT')
            mesh_obj.select_set(True)
            bpy.context.view_layer.objects.active = mesh_obj

            bpy.ops.wm.obj_export(
                filepath=output_file,
                export_selected_objects=True,
                export_uv=True,
                export_normals=True,
                export_materials=True,
                apply_modifiers=True
            )

            exported_files.append(output_file)
            frame_num += 1

    print(f"Exported {frame_num} frames to {output_dir}")
    return exported_files

def create_iqm_config(output_dir):
    """Create IQM configuration file for animations"""
    config_path = os.path.join(output_dir, "model.iqe")

    with open(config_path, 'w') as f:
        f.write("# IQM animation config for Xonotic player model\n")
        f.write("# Generated by export_player_model.py\n\n")

        frame_offset = 0
        for anim_name, anim_data in XONOTIC_ANIMS.items():
            frame_count = anim_data['end'] - anim_data['start'] + 1
            loop = "loop" if anim_data['loop'] else ""

            f.write(f"animation {anim_name}\n")
            f.write(f"framerate {anim_data['fps']}\n")
            f.write(f"start {frame_offset}\n")
            f.write(f"frames {frame_count}\n")
            if loop:
                f.write(f"{loop}\n")
            f.write("\n")

            frame_offset += frame_count

    print(f"Created animation config: {config_path}")
    return config_path

def main():
    output_path = get_output_path()
    output_dir = os.path.dirname(output_path) or '/tmp'
    frames_dir = os.path.join(output_dir, 'frames')

    print("=" * 50)
    print("Xonotic Player Model Exporter")
    print("=" * 50)
    print(f"Output: {output_path}")
    print("")

    # Export frames
    exported = export_to_obj_frames(frames_dir)

    if exported:
        # Create config
        create_iqm_config(frames_dir)

        print("")
        print("Next steps:")
        print(f"  1. cd {frames_dir}")
        print(f"  2. /path/to/iqm {output_path} frame_*.obj")
        print("")
        print("Or use the IQM tool with animation config")
    else:
        print("Export failed!")

if __name__ == "__main__":
    main()
